name: Build Distributions

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build-apple:
    name: Build macOS (Apple Silicon)
    runs-on: macos-latest
    outputs:
      artifact-folder: ${{ steps.upload.outputs.artifact-folder }}
    steps:
      - uses: actions/checkout@v4

      - name: Configure Node caching
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm-

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
        timeout-minutes: 5

      - name: Build distribution (macOS Apple Silicon)
        env:
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run build:mac -- --publish always

      - name: Create README
        run: |
          echo "More information: https://github.com/jeremybmerrill/meaningfully" > dist/README.txt

      - name: Upload artifact (macOS Apple Silicon)
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: meaningfully-macOS
          path: |
            dist/meaningfully-${{ github.ref_name }}.dmg
            dist/README.txt

  build-intel:
    name: Build macOS (Intel)
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4

      - name: Configure Node caching
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm-

      - name: Install brew dependencies
        run: brew install pkg-config cairo pango libjpeg giflib librsvg

      - name: Install npm deps
        run: npm install

      - name: Run tests
        run: npm test
        timeout-minutes: 5

      - name: Build distribution (macOS Intel)
        env:
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run build:mac -- --publish always

      - name: Create README
        run: 'echo "More information: https://github.com/jeremybmerrill/meaningfully" > dist/README.txt'

      - name: Upload artifact (macOS Intel)
        uses: actions/upload-artifact@v4
        with:
          name: meaningfully-macOS-intel
          path: |
            dist/meaningfully-${{ github.ref_name }}.intel.dmg
            dist/README.txt

  build-windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure Node caching
        uses: actions/cache@v4
        with:
          path: ~\AppData\Local\npm-cache
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm-

      - name: Install MSYS2
        run: choco install msys2 -y --no-progress

      - name: Install GTK3 development dependencies via MSYS2
        run: |
          "C:\tools\msys64\usr\bin\bash.exe" -c "pacman -Syu --noconfirm"
          "C:\tools\msys64\usr\bin\bash.exe" -c "pacman -S mingw-w64-x86_64-gtk3 --noconfirm"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
        timeout-minutes: 5

      - name: Build distribution (Windows)
        env:
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run build:win -- --publish always

      - name: Create README
        run: 'echo "More information: https://github.com/jeremybmerrill/meaningfully" > dist\README.txt'

      - name: Upload artifact (Windows)
        uses: actions/upload-artifact@v4
        with:
          name: meaningfully-windows
          path: |
            dist/meaningfully-${{ github.ref_name }}.exe
            dist/meaningfully-${{ github.ref_name }}-portable.exe
            dist\README.txt

  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure Node caching
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm-

      - name: Install Linux Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev libarchive-tools libfuse2 libgtk-3-0 libnss3 libxshmfence1 libatk-bridge2.0-0 libx11-xcb1 libxcb-dri3-0 libxcomposite1 libxcursor1 libxdamage1 libxfixes3 libxi6 libxrandr2 libxtst6 libgbm1 libpangocairo-1.0-0 libpango-1.0-0 libcairo2 libatspi2.0-0
          # sudo snap install snapcraft --classic

      - name: Install dependencies
        run: npm install
    
      - name: Run tests
        run: npm test
        timeout-minutes: 5

      - name: Build distribution (Linux)
        env:
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}          
        run: npm run build:linux -- --publish always

      - name: Create README
        run: 'echo "More information: https://github.com/jeremybmerrill/meaningfully" > dist/README.txt'

      - name: Upload artifact (Linux)
        uses: actions/upload-artifact@v4
        with:
          name: meaningfully-linux
          # add back once fixed dist/meaningfully-${{ github.ref_name }}.snap

          path: |
            dist/meaningfully-${{ github.ref_name }}.deb
            dist/meaningfully-${{ github.ref_name }}.AppImage
            dist/README.txt
    
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs:
      - build-apple
      - build-intel
      - build-windows
      - build-linux
    steps:
      - uses: actions/checkout@v4

      - name: Download macOS (Apple Silicon) artifact
        uses: actions/download-artifact@v2
        with:
          name: meaningfully-macOS
          path: ./artifacts/macOS

      - name: Download macOS (Intel) artifact
        uses: actions/download-artifact@v2
        with:
          name: meaningfully-macOS-intel
          path: ./artifacts/macOS-intel

      - name: Download Windows artifact
        uses: actions/download-artifact@v2
        with:
          name: meaningfully-windows
          path: ./artifacts/windows

      - name: Download Linux artifact
        uses: actions/download-artifact@v2
        with:
          name: meaningfully-linux
          path: ./artifacts/linux

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload macOS (Apple Silicon) DMG
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/macOS/meaningfully-${{ github.ref_name }}.dmg
          asset_name: meaningfully-${{ github.ref_name }}.dmg
          asset_content_type: application/x-apple-diskimage

      - name: Upload macOS (Intel) DMG
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/macOS-intel/meaningfully-${{ github.ref_name }}.intel.dmg
          asset_name: meaningfully-${{ github.ref_name }}-intel.dmg
          asset_content_type: application/x-apple-diskimage

      - name: Upload Windows NSIS Installer
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/windows/meaningfully-${{ github.ref_name }}.exe
          asset_name: meaningfully-${{ github.ref_name }}.exe
          asset_content_type: application/vnd.microsoft.portable-executable

      - name: Upload Windows Portable Executable
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/windows/meaningfully-${{ github.ref_name }}-portable.exe
          asset_name: meaningfully-${{ github.ref_name }}-portable.exe
          asset_content_type: application/vnd.microsoft.portable-executable

      - name: Upload Linux DEB
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/linux/meaningfully-${{ github.ref_name }}.deb
          asset_name: meaningfully-${{ github.ref_name }}.deb
          asset_content_type: application/vnd.debian.binary-package

      # - name: Upload Linux Snap
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: ./artifacts/linux/meaningfully-${{ github.ref_name }}.snap
      #     asset_name: meaningfully-${{ github.ref_name }}.snap
      #     asset_content_type: application/octet-stream

      - name: Upload Linux AppImage
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/linux/meaningfully-${{ github.ref_name }}.AppImage
          asset_name: meaningfully-${{ github.ref_name }}.AppImage
          asset_content_type: application/vnd.appimage